name: Docker

on:
  push:
    branches: [main]
#  release:
#    types: [published]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  IMAGE_NAME: enmapbox_base-win

jobs:
  push:
    name: Push image to Docker Hub
    runs-on: windows-2022
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build image
        run: docker build . --file win/Dockerfile --tag $IMAGE_NAME
      - name: Push image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          echo VERSION=$VERSION
          echo DOCKER=$DOCKER_USER/$IMAGE_NAME:$VERSION
          docker tag $IMAGE_NAME $DOCKER_USER/$IMAGE_NAME:$VERSION
          docker push $DOCKER_USER/$IMAGE_NAME:$VERSION