name: Docker

on:
  push:
    branches: [main]
#  release:
#    types: [published]

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  IMAGE_NAME: enmapbox_base-win

jobs:
  push:
    name: Push image to Docker Hub
    runs-on: windows-2022
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker login
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        shell: pwsh
      - name: Build image
        run: docker build win --file Dockerfile --tag ${{ env.IMAGE_NAME }}
        shell: pwsh
      - name: Push image
        run: |
          $VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if ("${{ github.ref }}" -match "refs/tags/") { $VERSION = $VERSION -replace '^v', '' }
          if ($VERSION -eq "main") { $VERSION = "latest" }
          Write-Host "VERSION=$VERSION"
          Write-Host "DOCKER=${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:$VERSION"
          docker tag ${{ env.IMAGE_NAME }} ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:$VERSION
          docker push ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:$VERSION
        shell: pwsh